#!/usr/local/bin/zsh
npx icon-gen -i src/images/capenta.svg -o static/favicons --ico
rm static/favicons/favicon-*.png
rm static/favicons/app.icns
rm static/favicons/app.ico
npx svgexport src/images/capenta.svg static/logos/logo-48.png 48:
npx svgexport src/images/capenta.svg static/favicons/mstile-150x150.png 150:
npx svgexport src/images/capenta.svg static/favicons/favicon-32x32.png 32:
npx svgexport src/images/capenta.svg static/favicons/favicon-16x16.png 16:
npx svgexport src/images/capenta.svg static/favicons/apple-touch-icon.png 180:
npx svgexport src/images/capenta.svg static/favicons/android-chrome-512x512.png 512:
npx svgexport src/images/capenta.svg static/logos/logo-512x512.png 512:
npx svgexport src/images/capenta.svg static/favicons/android-chrome-192x192.png 192:
npx svgexport src/images/capenta.svg static/logos/logo-192x192.png 192:
npx svgexport src/images/capenta.svg static/logos/logo-1024.png 1024:
